services:
  cvitae:
    build:
      context: "."
      dockerfile: Dockerfile
    volumes:
      - "./app:/app"
    ports:
      - "8000:8000"
    command: bash -c 'source cli.sh && mig && run'

  # cvitae_linter:
  #   image: ghcr.io/super-linter/super-linter:latest
  #   build:
  #     context: "."
  #   environment:
  #     - RUN_LOCAL=true

  #   volumes:
  #     - "./app:/tmp/lint"