# Generated by Django 5.0.6 on 2024-08-15 22:27

import django.db.models.deletion
import django_lifecycle.mixins
import llm.database.collector
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('version', models.TextField(blank=True, null=True)),
                ('token', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PromptPreface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('version', models.TextField(blank=True, null=True)),
                ('formatting', models.TextField(blank=True, null=True)),
                ('instruction', models.TextField(blank=True, null=True)),
                ('context_text', models.TextField(blank=True, null=True)),
                ('addresses', models.ManyToManyField(blank=True, to='api.address')),
                ('companies', models.ManyToManyField(blank=True, to='api.company')),
                ('educations', models.ManyToManyField(blank=True, to='api.education')),
                ('internships', models.ManyToManyField(blank=True, to='api.internship')),
                ('jobpostings', models.ManyToManyField(blank=True, to='api.jobposting')),
                ('letters', models.ManyToManyField(blank=True, to='api.coverletter')),
                ('persons', models.ManyToManyField(blank=True, to='api.person')),
                ('qualifications', models.ManyToManyField(blank=True, to='api.qualification')),
                ('skills', models.ManyToManyField(blank=True, to='api.skill')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PromptClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('version', models.TextField(blank=True, null=True)),
                ('prompt', models.TextField(blank=True, null=True)),
                ('preface_fields', models.JSONField(blank=True, default=llm.database.collector.preface_fields, null=True)),
                ('template', models.TextField(blank=True, help_text='auto generated template from preface config', null=True)),
                ('refresh', models.BooleanField(default=False, help_text='regenerate the template')),
                ('refresh_preface_fields', models.BooleanField(default=False, help_text='reset the preface fields list')),
                ('response_json', models.JSONField(blank=True, help_text='llm response to the template as json', null=True)),
                ('response_text', models.TextField(blank=True, help_text='llm response to the template as text', null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='llm.llmclient')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('prefaces', models.ManyToManyField(blank=True, to='llm.promptpreface')),
            ],
            options={
                'abstract': False,
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
